default_context:
  project_name: 'helloWorld'
  project_slug: 'helloworld'
  domain_main: 'helloworld.com'
  domain_staging: 'stag.helloworld.com'
  docker_swarm_stack_name_main: 'helloworld-com'
  docker_swarm_stack_name_staging: 'stag-helloworld-com'
  secret_key: '99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f'
  first_superuser: 'admin'
  first_superuser_password: 'admin'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.helloworld.com, https://stag.helloworld.com, https://helloworld.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@helloworld.com'
  postgres_password: 'admin'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'helloworld.com'
  traefik_constraint_tag_staging: 'stag.helloworld.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin'
  sentry_dsn: ''
  docker_image_prefix: 'hello_world_'
  docker_image_backend: 'hello_world_backend'
  docker_image_celeryworker: 'hello_world_celeryworker'
  docker_image_frontend: 'hello_world_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
